name: atropim_489afea

services:
  app:
    platform: linux/amd64
    image: yorem/atropim:489afea@sha256:eebac45fd6fa9624ca47515b4a7bd7b3baaf0e25a6c31e77e7321970111c0faa
    ports:
      - "18083:80"
    volumes:
      - atropim_489afea_db:/var/lib/mysql
      - atropim_489afea_data:/var/www/html/data
      - atropim_489afea_upload:/var/www/html/upload

volumes:
  atropim_489afea_db:
  atropim_489afea_data:
  atropim_489afea_upload:
