name: grafana_11_2_0
services:
  app:
    image: yorem/grafana:11.2.0@sha256:9924c7fe0effe4a5fea08b3451905de54f09fde9d1589463a5f2d02d9ec158bc
    platform: linux/amd64
    ports:
      - "18573:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=AdminPassword123!
    restart: unless-stopped
