name: plone-6-0-11

services:
  plone:
    image: yorem/plone:6.0.11@sha256:e73ae6e9864e43d4d49169f9fda09012d48c7720e8e204a8b0304b764600923b
    platform: linux/amd64
    ports:
      - "18575:8080"
    environment:
      SITE: Plone
      PROFILES: "plone.app.caching:default"
    restart: unless-stopped
