name: mautic-5-0-4

services:
  application:
    image: yorem/mautic:5.0.4@sha256:2cca12c2ec7fac66e04b3423523b05f8658572e68011e8ead4159f6fde09c79e
    ports:
      - "18518:80"
    volumes:
      - ./opcache.ini:/usr/local/etc/php/conf.d/zz-disable-opcache.ini:ro
      - application-data:/var/www/html/var
      - application-media:/var/www/html/media/files
      - application-db:/var/lib/mysql

volumes:
  application-data:
  application-media:
  application-db:
