CREATE DATABASE IF NOT EXISTS `benchmark`;
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'benchmark-only';
GRANT ALL PRIVILEGES ON `benchmark`.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
