services:
  application:
    image: asteriskax001/sop-mediawiki:1.41.1
    platform: linux/amd64
    ports:
      - "18519:80"
    volumes:
      - mediawiki-data:/var/www/html/images
      - mediawiki-db:/var/lib/mysql

volumes:
  mediawiki-data:
  mediawiki-db:

