services:
  application:
    image: yorem/mediawiki:1.41.1@sha256:b45fb686c2bd6740307433eb0d3a028f249ef6ef35d489b3ee1154f7af51df81
    platform: linux/amd64
    ports:
      - "18519:80"
    volumes:
      - mediawiki-data:/var/www/html/images
      - mediawiki-db:/var/lib/mysql

volumes:
  mediawiki-data:
  mediawiki-db:

