services:
  application:
    image: yorem/joomla:5.1.1@sha256:7287c440475adb0d35dada0ac970f37798bbeff801a0cdb48d68dbf240d26128
    ports:
      - "18211:80"
    volumes:
      - application-db:/var/lib/mysql
      - application-images:/var/www/html/images
      - application-media:/var/www/html/media
      - application-cache:/var/www/html/cache
      - application-tmp:/var/www/html/tmp

volumes:
  application-db:
  application-images:
  application-media:
  application-cache:
  application-tmp:
