name: redmine-5-1-2

services:
  application:
    image: yorem/redmine:5.1.2@sha256:d406bb68a7f705f9ec97e1ac1f62e73dd1c487fabf414bf254c0c05ee2ea6a60
    ports:
      - "18511:80"
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-log:/usr/src/redmine/log
      - redmine-tmp:/usr/src/redmine/tmp
      - redmine-db:/var/lib/mysql

volumes:
  redmine-files:
  redmine-log:
  redmine-tmp:
  redmine-db:
