name: crushftp_10_0_0_default

services:
  web:
    image: yorem/crushftp:10.0.0@sha256:d6eca9c6a3a9d09debde37590ce91b3b1f8bb7587368639cc847487515e67d03
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "18634:8080"
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-AdminPassword123!}
