services:
  application:
    image: yorem/wordpress:6.5.3@sha256:f4ccc154623599cd25843081ef340cdfdfdaa08d86adcce0c0586c6b95f71eb7
    platform: linux/amd64
    ports:
      - "18513:80"
    volumes:
      - wordpress-data:/var/www/html/wp-content
      - wordpress-db:/var/lib/mysql

volumes:
  wordpress-data:
  wordpress-db:

