services:
  application:
    image: yorem/oscommerce:2.4.2@sha256:e28f0aa26ae2fef9d4f9e04b8fe07cccdb2397da789f7542c17fd9b37cb34494
    ports:
      - "18402:80"
    volumes:
      - oscommerce-db:/var/lib/mysql
      - oscommerce-work:/var/www/html/includes/OSC/Work

volumes:
  oscommerce-db:
  oscommerce-work:

