services:
  application:
    image: yorem/glpi:10.0.15@sha256:1f60883f24640fc1197b428340a5878b31b9ceec26cbdfb85527fbb25eda7e9d
    ports:
      - "18514:80"
    volumes:
      - glpi-data:/var/www/html/files
      - glpi-config:/var/www/html/config
      - glpi-db:/var/lib/mysql

volumes:
  glpi-data:
  glpi-config:
  glpi-db:

