name: mall_1_0_3

services:
  application:
    platform: linux/amd64
    image: nnin/sop-mall:1.0.3
    ports:
      - "18085:80"
    volumes:
      - mall_1_0_3_mysql:/var/lib/mysql
      - mall_1_0_3_redis:/var/lib/redis
      - mall_1_0_3_logs:/var/log/mall

volumes:
  mall_1_0_3_mysql:
  mall_1_0_3_redis:
  mall_1_0_3_logs:
