<?php
$sugar_config_si = array (
    'setup_db_host_name' => 'db',
    'setup_db_database_name' => 'sugarcrm',
    'setup_db_drop_tables' => 0,
    'setup_db_create_database' => 1,
    'setup_db_type' => 'mysql',
    'setup_db_admin_user_name' => 'root',
    'setup_db_admin_password' => 'sugarcrm_root_password',
    'setup_db_pop_demo_data' => false,
    'demoData' => 'no',
    'setup_site_admin_user_name' => 'admin',
    'setup_site_admin_password' => 'admin',
    'setup_site_url' => 'http://localhost:18629',
    'setup_system_name' => 'SugarCRM',
    'default_currency_iso4217' => 'USD',
    'default_currency_name' => 'US Dollar',
    'default_currency_significant_digits' => '2',
    'default_currency_symbol' => '$',
    'default_date_format' => 'Y-m-d',
    'default_time_format' => 'H:i',
    'default_decimal_seperator' => '.',
    'default_export_charset' => 'ISO-8859-1',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator' => ',',
    'export_delimiter' => ',',
);
