name: prometheus_2_53_0
services:
  app:
    image: yorem/prometheus:2.53.0@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    platform: linux/amd64
    ports:
      - "18559:9090"
    restart: unless-stopped
