application: lets-chat
version: 0.4.8
topology: compose
deployment_mode: native_compose
delivery_method: DOCKERHUB
dockerhub_namespace: yorem
compose_file: docker/compose.yaml
source:
  repository: https://github.com/sdelements/lets-chat
  commit: a5e8b2d5977fedc167e1efb03a4f80121da4842e
runtime:
  node: "0.12.15"
  database: mongo:4.4
ports:
  host_port: 18631
  container_port: 5000
credentials:
  admin_username: admin
  admin_password: AdminPassword123!
resources:
  users: resources/users.yaml
  roles: resources/roles.yaml
  login: resources/login.sh
scripts:
  up: scripts/up.sh
  healthcheck: scripts/healthcheck.sh
  reset: scripts/reset.sh
source_metadata: source/source.yaml
source_checksums: source/SHA256SUMS

services:
  app:
    image: yorem/lets-chat:0.4.8@sha256:5b923d428176250653530fdac8a9f925043f30c511b77701662d7f8fab74961c
    tag: 0.4.8
    digest: sha256:5b923d428176250653530fdac8a9f925043f30c511b77701662d7f8fab74961c
    platform: linux/amd64
  mongo:
    image: mongo:4.4@sha256:4be76f674fc4b27859816811b8baa3c51830eb1dbf4ca81a51e26b79edd662ef
    tag: "4.4"
    digest: sha256:4be76f674fc4b27859816811b8baa3c51830eb1dbf4ca81a51e26b79edd662ef
    platform: linux/amd64
