name: mattermost_9_11_0_default

services:
  db:
    image: postgres:16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
    platform: linux/amd64
    restart: unless-stopped
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mmuser -d mattermost"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 3s
    volumes:
      - mattermost_db_data:/var/lib/postgresql/data

  app:
    image: yorem/mattermost:9.11.0@sha256:335db2833330323d9a9f43313429f4b16b497067644660acfdfc2424ab04d2de
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "18609:8065"
    environment:
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://127.0.0.1:18609
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - mattermost_data:/mattermost/data

volumes:
  mattermost_db_data:
  mattermost_data:
