services:
  application:
    image: yorem/phpmyadmin:4.7.9@sha256:afd5d342644af52c323bc60e4d54b64a84220c22b62b6cd0b56b4189ec1ab7a8
    ports:
      - "18379:80"
    volumes:
      - application-db:/var/lib/mysql
      - application-data:/var/www/html/data

volumes:
  application-db:
  application-data:
