services:
  application:
    image: yorem/wordpress:7.0.3-aio@sha256:004c2da991d835c426fbcb57ac98beaee1b7feeb6ceaa16f5bb80857eaafc7fd
    platform: linux/amd64
    ports:
      - "18513:80"
    volumes:
      - wordpress-data:/var/www/html/wp-content
      - wordpress-db:/var/lib/mysql

volumes:
  wordpress-data:
  wordpress-db:

