server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    set $base /srv/www/htdocs;
    root $base/b2evolution;

    include nginxconfig.io/security.conf;
    include nginxconfig.io/general.conf;

    access_log /var/log/nginx/access.log main;
    error_log /dev/stderr warn;

    set $no_cache 0;
    if ($arg_skipcache = 1) {
        set $no_cache 1;
    }

    index index.php;

    location ~^/(ping|status)$ {
        access_log off;
        allow 127.0.0.1;
        deny all;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/php-fpm.sock;
    }

    location / {
        index index.php;
        try_files $uri $uri/ @b2evo;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        try_files $uri /htsrv/getfile.php?$args;
        expires 7d;
        log_not_found off;
    }

    location @b2evo {
        rewrite ^(.*) /index.php?$1 last;
    }

    location /api/ {
        auth_basic off;
        rewrite "^/api/v(?<version>[^/]+)/(?<parameters>(.+))$" /htsrv/rest.php?api_version=$version&api_request=$parameters last;
    }

    location ~ \.php$ {
        include nginxconfig.io/php_fastcgi.conf;
    }
}
