services:
  application:
    image: asteriskax001/sop-gitlab:16.11.2-ce.0
    ports:
      - "18527:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
